[build]
  command = "npm run netlify-build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/redirect?code=:splat"
  status = 200
  force = true
